---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-jenkins-centos
    image: docker.io/centos:8
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports: # remove this option when performing CI tets
      - 0.0.0.0:8080:8080/tcp
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ../../tests/


